### ISSUE TITLE
Add small exercises!

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#1]
We're looking for the curriculum to include helpful guides for completing a set of exercises (think small programming challenges that could be completed in the Scala REPL).

Ideas:
- String manipulation
- List manipulation 
- Anything that makes use of Scala language features

More inspiration:
- https://www.scala-exercises.org/
- https://adriann.github.io/programming_problems.html
- http://codekata.com/
- https://projecteuler.net/

The target audience is beginning programmers.

**Comment by mbren** [comment]
The first half of the book, [Scala for the Impatient, is available for free on the Lightbend website](https://www.lightbend.com/resources/e-book/scala-for-the-impatient). It is a good resource for beginners and each chapter ends with a set of exercises that reinforce the content.
