### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by heathermiller** [scalabridge/curriculum#16]
Maybe one way to grow momentum here is via a gitter channel? This way there's a 24/7 line of communication possible to deposit and discuss ideas?

**Comment by DagnyTagg2013** [comment]
AGREED!  I actually like Slack for collaboration. You can easily open up separate topic groups; and join forums that you're interested in.  Would really LOVE to see collaboration/chat/discussion on related topics on feminism manifested in software creation, as well as stand-up comedy(!)  I joined this group mostly for the social opportunity to be able to find a "tribe" of like-minded women who love to share ideas and enthusiasm for feminism, software, business creation, as well as the fun (and sometimes not) life experiences for women in software!

**Comment by robinske** [comment]
done! @heathermiller @DagnyTagg2013 https://gitter.im/scalabridge/curriculum
