### ISSUE TITLE
Add "level" for resources

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#19]
"beginner" "intermediate" "advanced" or more notes about what the resource gives the person.

Let's give them colors instead of words so we can break it out into:
- Blue - little or no programming experience
- Green - resources assumes prior programming experience but no scala experience
- Red - you know some scala, now what

https://github.com/scalabridge/curriculum/blob/master/resources.md

**Comment by tim-ruhland** [comment]
Great idea on the colors. Like it a lot.

**Comment by tim-ruhland** [comment]
Will need to create an HTML version (for website?) to implement color coding. GitHub Markdown doesn't support color AFAIK.

**Comment by robinske** [comment]
Closing this out - resources were separated by level in https://github.com/scalabridge/curriculum/commit/f93acb7642026a501ea4cf83b39f86fabaf58254
