### ISSUE TITLE
Ideas for a project?

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#2]
Students will have the opportunity to work on a small project or program during the workshop. What should this be? 

Considerations:
- Feedback is important (visual, interactive, etc.)
- Make it flexible/creative so the attendee can engage with the project
- Something that can be built iteratively (not everyone has to be at the same level, and people can continue to build on it after the workshop)
- The workshop is intended to give people not only the building blocks of Scala, but to evaluate whether they want to continue learning Scala after the workshop. This project should "show off" Scala (keep in mind that attendees will be more beginner level)
- Do we want to provide any boilerplate? (samples! examples!)

Ideas:
- Use the Twitter API and do something with a tweet stream
- Find the hottest day in the last year for a given zip code (let the user input the zip code of their choice)
- Build a calculator
- Game
- Swing (or other desktop GUI) application
- Play (or other web) application
- Image generation/manipulation (e.g. draw fractals, image resizing)
- Chat application (more advanced)
- Command Line Twitter client (use code they wrote to tweet!)

**Comment by robinske** [comment]
ClojureBridge calls this a "capstone" app and gives several options - see https://clojurebridge.github.io/curriculum/#/1 for a list

**Comment by k4y3ff** [comment]
Fancy running into you 'round these parts, @robinske! 😉 🌈 

A question:

> Something that can be built iteratively (not everyone has to be at the same level, and people can continue to build on it after the workshop)

How varying do you anticipate these levels being?

In particular, if you anticipate any folks coming to your ScalaBridge workshops who have data science backgrounds (e.g. analysis-type work in Python and R), some of the more software-y projects will be less ideal--like writing a Swing application, Play application, or chat application. If you anticipate folks coming to the workshops who have limited experience coding overall, doing stuff involving APIs will also be too complex for a 1-2 day workshop.

Though there's a web-application-type project in the ClojureBridge curriculum, that was the first project we started with, and we quickly abandoned it for projects that involved no web/desktop application boilerplate, except for workshops that were specifically for people experienced with web development.

Having the final project be something calculator-esque works well--meaning, having the final project involve transformations, but not necessarily interfacing with another software project. Another option is doing light graphics stuff, which is what many of our ClojureBridge workshops do now!

We use [Quil](http://quil.info/) for that, but I don't know that a similarly approachable Processing wrapper exists for Scala. @noelwelsh wrote [Doodle](https://github.com/underscoreio/doodle), which is similar in spirit, IMHO! He also used it for the Underscore entry-level whitepaper-type tutorial on their website, though, so probably chat with him if it seems promising.

**Comment by noelwelsh** [comment]
In addition to Doodle mentioned above, here are some case studies that may be appropriate for more advanced students:
- a chat web app, called [Doodlebot](https://github.com/underscoreio/doodlebot) for legacy reasons (it was originally going to be a Twitter bot but implementing OAuth was too much hassle);  and
- a terminal based [chat implementation using scalaz-stream](https://gist.github.com/noelwelsh/cc5f088aeedc73635ddc78bda89e952d).

Generally happy to work on any of these to develop them into something suitable for ScalaBridge.

Examples of using the current version of Doodle are in [v2 of Creative Scala](https://github.com/underscoreio/creative-scala/tree/feature/v2).

**Comment by robinske** [comment]
awesome, thanks @noelwelsh and @kpfell !

**Comment by DagnyTagg2013** [comment]
Hi there!

I have in my repo the following that could be helpful to teach, but can be expanded further:
- Word Count Application -- showing the (basic) power of scalability for Data Science 
- Echo Server Application -- showing the (basic) power of responsive Web Apps
- Event Streaming Example -- showing the (basic) power of functional for Data Pipelines

Let me know if you may have interest in this for advanced beginners who may want to tackle more?
I feel there's a lack of Women's Coding resources to serve this set of 'Advanced Beginners'!

Dagny T
