### ISSUE TITLE
Slack Channel for helping remotely

### ISSUE THREAD

**Issue by DagnyTagg2013** [scalabridge/curriculum#27]
Hi there!  

My kid has classes on Sat now that school is in.  I would love to chat and contribute remotely; and was hoping someone could post a link to enter a Slack group for participation!

THANK YOU for organizing!
Dagny T

**Comment by robinske** [comment]
Check out the Gitter channel! https://gitter.im/scalabridge/curriculum

**Comment by DagnyTagg2013** [comment]
THANK YOU!  Sorry, busy with kidstuff today and wasn't able to attend!
