### ISSUE TITLE
Teach on Immutability via Basic List

### ISSUE THREAD

**Issue by DagnyTagg2013** [scalabridge/curriculum#28]
Much of the scaling power of Scala lies in the core concept of Immutability.
Newbies need some kind of succinct context-framing around this to make their learning time a productive investment.

They can get this from exercises in the  "Atomic Scala" book.

Please see '/curriculum/exercises' repo for 'ListBasics.sc' overview on first attempt to teach to Newbies with needed context-framing.  Disclaimer:  I'm a Newbie who just Googles up stuff.

NOTE:  An *.sc is just an IntelliJ Scala Worksheet, which is a Scala Script that can be run within that IDE; or equivalently, pasted and run in the command-line REPL.

**Comment by robinske** [comment]
Cool, good idea - I'll take a look!

**Comment by robinske** [comment]
Closing this as included in the Creative Scala material!
