### ISSUE TITLE
Aggregate resources for reference and further learning

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#3]
A start:

| Name | Org | Link |
| --- | --- | --- |
| Scala Exercises | 47 degrees | https://www.scala-exercises.org/ |
| Coursera Scala Specialization | Scala Center, free without certificate | https://www.coursera.org/specializations/scala |
| Scala School | Twitter | https://twitter.github.io/scala_school/ |
| Effective Scala | Twitter | http://twitter.github.io/effectivescala/ |
| Creative Scala | Underscore | Currently in draft form |

**Comment by DagnyTagg2013** [comment]
On Googling for code samples; I found Odersky's intro book to be pretty good, but I'm a newbie:
http://www.scalacommunity.com/2014-11-best-scala-books

**Comment by xinhhuynh** [comment]
This is a good book for beginners: Atomic Scala, by Bruce Eckel and Dianne Marsh: http://www.atomicscala.com/

**Comment by mbren** [comment]
Here are some more resources:
- Scala for the Impatient book: Get the free sample chapters at https://www.lightbend.com/resources/e-book/scala-for-the-impatient
- Functional Programming in Scala book: (free sample chapters at https://www.lightbend.com/resources/e-book/functional-programming-in-scala)
- Programming in Scala book (First edition is available for free online here: http://www.artima.com/pins1ed/) 
- Cheatsheet from the Coursera Scala Course https://github.com/lampepfl/progfun-wiki/blob/gh-pages/CheatSheet.md
- Scala Standard Library documentation: http://www.scala-lang.org/api/current/#package
- Scala language specification: http://www.scala-lang.org/files/archive/spec/2.11/
- Scala Programming Language github repo: https://github.com/scala/scala
- Essential Scala - Six Core Concepts for Learning Scala http://downloads.typesafe.com/website/presentations/ScalaDaysSF2015/essential-scala.pdf
- Scala by Example book http://www.scala-lang.org/docu/files/ScalaByExample.pdf

**Comment by DagnyTagg2013** [comment]
OH!  Everyone has GOT to watch this woman's (sorry, I don't know a better term:  BadAss) Scala YouTube videos!  Even though I'd taken Odersky's MOOC on Functional Programming; I didn't "get" some key concepts until after I watched this woman explain things from the perspective of an in-the-trenches coder with a wicked sense of humor and just an awesome attitude towards teaching the unwashed masses (me!):  http://nerd.kelseyinnis.com/blog/2013/11/12/idiomatic-scala-the-for-comprehension/

**Comment by DagnyTagg2013** [comment]
So, here's another one.  This presentation is awesome in that it strikes the super-tricky balance between women's empowerment; and appealing to hipster tech Bros too(!)  https://www.youtube.com/watch?v=OOvL6QAxRK4

**Comment by tim-ruhland** [comment]
[The Neophyte's Guide to Scala](http://danielwestheide.com/scala/neophytes.html)

**Comment by robinske** [comment]
https://github.com/scalabridge/curriculum/blob/master/resources.md
