### ISSUE TITLE
Add "cheat sheet" for core library & methods

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#5]
~1 pager that people can reference, trimmed down to the essentials

**Comment by mbren** [comment]
Maybe we could link to this awesome cheatsheet from the Coursera Scala Course https://github.com/lampepfl/progfun-wiki/blob/gh-pages/CheatSheet.md

**Comment by robinske** [comment]
oh @mbren that's an excellent resource! we can use a lot of that/simplify it for the scope of this course!
