### ISSUE TITLE
Add curriculum "schedule"

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#9]
Once we've developed more of pieces, let's put it all together in a "schedule" for what the workshop day will look like

Rough outline:
- Introductions
- Why Scala
- Programming fundamentals
- Exercises
- Project

Schedule is a loose term since students will progress at different paces.

**Comment by k4y3ff** [comment]
Re: this, I'd consider having exercises dispersed throughout the day, vs. their own section!

I find that people struggle to focus on a lecture-type thing for more than 20-30 minutes at a time, so I try to alternate between lectures and exercises. This results in something roughly like:
- 9am-9:15am - Why Even
- 10:30-10:45am - Short Break
- 12pm-1pm - Lunch and Gossip
- 2:30pm-2:45pm - Short Break and Cookies
- 3:30-5pm or 2:45pm-4pm - Project and Show & Tell
- EOD
- Afterwards - Use Sponsor Money on Fun Things

Where "Use Sponsor Money on Fun Things" looks like, well... IDK. Lots of things! In Austin, we all went to Pinballz, and one of the sponsors got us a bunch of coins. I feel like Portlanders did something similar and went to Ground Kontrol, but I might be making that up.

All the other times are alternating back and forth between lessons.

Another upside to this is that you can review exercises as you go, so everyone sees the solutions and can build on them in subsequent exercises--which helps even out the pace of the class.

**Comment by robinske** [comment]
First draft done in https://github.com/scalabridge/curriculum/commit/2fb548465e5cdb2267b930c42a9e3a979af70e72
